services:
    database:
        image: postgres
        volumes:
            - ./database/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'

    backend:
        depends_on:
            - database
        build: backend
        command: python app/manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend/app:/code/app
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '8000:8000'

    frontend:
        depends_on:
            - backend
        build: frontend
        command: npm run dev
        volumes:
            - ./frontend/pages:/code/pages
            - ./frontend/public:/code/public
            - ./frontend/styles:/code/styles
            - ./frontend/components:/code/components
        ports:
            - '3000:3000'
